#pragma once

#include <stdlib.h>
#include "types.h"
#include "global.h"
hh_entity hh_mtd_lvl4_enemy[16] = {
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){339, 93},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {
            .frame0 = HH_TM_SLIME_OFFSET,
            .palette = 2,
            .fam = (hh_s_ppu_loc_fam_entry){
                .horizontal_flip = false,
                .vertical_flip = false,
                .palette_index = 2,
                .tilemap_index = HH_TM_SLIME_OFFSET,
            }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){318, 245},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){558, 422},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){109, 965},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){477, 874},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){117, 1830},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){532, 1834},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){345, 1678},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){80, 301},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){282, 589},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){445, 673},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){364, 1160},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){198, 1321},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){392, 1418},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){133, 1143},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
    {
        .object_type = jumping_slime,
        .is_grounded = false,
        .is_hit = false,
        .pos = (vec2){263, 1674},
        .size = (vec2){16, 16},
        .vel = (vec2){0, 0},
        .hp = g_hh_slime_hp,
        .speed = g_hh_slime_speed,
        .radius = g_hh_slime_radius,
        .render = {.frame0 = HH_TM_SLIME_JUMPABLE_OFFSET, .palette = 2, .fam = (hh_s_ppu_loc_fam_entry){
                                                                   .horizontal_flip = false,
                                                                   .vertical_flip = false,
                                                                   .palette_index = 2,
                                                                   .tilemap_index = HH_TM_SLIME_JUMPABLE_OFFSET,
                                                               }},
    },
};
const vec2 lvl4_start_pos_enemy[16] = {
    {339, 93},
    {318, 245},
    {558, 422},
    {109, 965},
    {477, 874},
    {117, 1830},
    {532, 1834},
    {345, 1678},
    {80, 301},
    {282, 589},
    {445, 673},
    {364, 1160},
    {198, 1321},
    {392, 1418},
    {133, 1143},
    {263, 1674},
};
const vec2 hh_lvl4_player_start_pos = (vec2){.x = 120, .y = 80};
const vec2 lvl4_boss_spawn_point = (vec2){.x = 331, .y = 2183};
const int lvl4_enemy_size = 16;
