#pragma once

#include "global.h"
#include "types.h"
#include <stdlib.h>

hh_entity hh_mtd_lvl2_enemy[13] = {
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){400, 108},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){384, 221},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){60, 302},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){556, 356},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){250, 680},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){604, 795},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){74, 1215},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){565, 1217},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){59, 505},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){494, 488},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){306, 850},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){237, 1033},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){394, 1030},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
};
const vec2 lvl2_start_pos_enemy[13] = {
	{400, 108}, {384, 221}, {60, 302}, {556, 356}, {250, 680}, {604, 795}, {74, 1215}, {565, 1217}, {59, 505}, {494, 488}, {306, 850}, {237, 1033}, {394, 1030},
};
const vec2 hh_lvl2_player_start_pos = (vec2){.x = 68, .y = 70};
const vec2 lvl2_boss_spawn_point	= (vec2){.x = 320, .y = 1465};
const int lvl2_enemy_size			= 13;
