#pragma once

#include "global.h"
#include "types.h"
#include <stdlib.h>
hh_entity hh_mtd_lvl1_enemy[12] = {
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){487, 370},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){750, 372},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){1008, 369},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){1194, 369},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){92, 346},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){265, 102},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){222, 352},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){557, 371},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){746, 187},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){880, 186},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = jumping_slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){1306, 184},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_JUMPABLE_OFFSET,
						}},
	},
	{
		.object_type = slime,
		.is_grounded = false,
		.is_hit		 = false,
		.pos		 = (vec2){1388, 180},
		.size		 = (vec2){16, 16},
		.vel		 = (vec2){0, 0},
		.hp			 = g_hh_slime_hp,
		.speed		 = g_hh_slime_speed,
		.radius		 = g_hh_slime_radius,
		.render		 = {.frame0	 = HH_TM_SLIME_OFFSET,
						.palette = 2,
						.fam =
							(hh_s_ppu_loc_fam_entry){
								.horizontal_flip = false,
								.vertical_flip	 = false,
								.palette_index	 = 2,
								.tilemap_index	 = HH_TM_SLIME_OFFSET,
						}},
	},
};
const vec2 lvl1_start_pos_enemy[12] = {
	{487, 370}, {750, 372}, {1008, 369}, {1194, 369}, {92, 346}, {265, 102}, {222, 352}, {557, 371}, {746, 187}, {880, 186}, {1306, 184}, {1388, 180},
};
const vec2 hh_lvl1_player_start_pos = (vec2){.x = 52, .y = 68};
const vec2 lvl1_boss_spawn_point	= (vec2){.x = 1300, .y = 346};
const int lvl1_enemy_size			= 12;
