set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property PACKAGE_PIN L2 [get_ports SPI_MOSI]

set_property PACKAGE_PIN J2 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports SPI_SR]
set_property PACKAGE_PIN H1 [get_ports SPI_SR]
set_property PULLDOWN true [get_ports SPI_SR]



set_property IOSTANDARD LVCMOS33 [get_ports HBLANK]
set_property PACKAGE_PIN K2 [get_ports HBLANK]

set_property IOSTANDARD LVCMOS33 [get_ports VBLANK]
set_property PACKAGE_PIN J1 [get_ports VBLANK]



set_property IOSTANDARD LVCMOS33 [get_ports SYSCLK]
set_property PACKAGE_PIN W5 [get_ports SYSCLK]

set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property PACKAGE_PIN T18 [get_ports RESET]

set_property IOSTANDARD LVCMOS33 [get_ports DBG_DISP_ADDR]
set_property PACKAGE_PIN R2 [get_ports DBG_DISP_ADDR]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_LEDS_OUT[0]}]
set_property PACKAGE_PIN L1 [get_ports {DBG_LEDS_OUT[15]}]
set_property PACKAGE_PIN P1 [get_ports {DBG_LEDS_OUT[14]}]
set_property PACKAGE_PIN N3 [get_ports {DBG_LEDS_OUT[13]}]
set_property PACKAGE_PIN P3 [get_ports {DBG_LEDS_OUT[12]}]
set_property PACKAGE_PIN U3 [get_ports {DBG_LEDS_OUT[11]}]
set_property PACKAGE_PIN W3 [get_ports {DBG_LEDS_OUT[10]}]
set_property PACKAGE_PIN V3 [get_ports {DBG_LEDS_OUT[9]}]
set_property PACKAGE_PIN V13 [get_ports {DBG_LEDS_OUT[8]}]
set_property PACKAGE_PIN V14 [get_ports {DBG_LEDS_OUT[7]}]
set_property PACKAGE_PIN U14 [get_ports {DBG_LEDS_OUT[6]}]
set_property PACKAGE_PIN U15 [get_ports {DBG_LEDS_OUT[5]}]
set_property PACKAGE_PIN W18 [get_ports {DBG_LEDS_OUT[4]}]
set_property PACKAGE_PIN V19 [get_ports {DBG_LEDS_OUT[3]}]
set_property PACKAGE_PIN U19 [get_ports {DBG_LEDS_OUT[2]}]
set_property PACKAGE_PIN E19 [get_ports {DBG_LEDS_OUT[1]}]
set_property PACKAGE_PIN U16 [get_ports {DBG_LEDS_OUT[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DBG_SWTC_IN[0]}]
set_property PACKAGE_PIN R2 [get_ports {DBG_SWTC_IN[15]}]
set_property PACKAGE_PIN T1 [get_ports {DBG_SWTC_IN[14]}]
set_property PACKAGE_PIN U1 [get_ports {DBG_SWTC_IN[13]}]
set_property PACKAGE_PIN W2 [get_ports {DBG_SWTC_IN[12]}]
set_property PACKAGE_PIN R3 [get_ports {DBG_SWTC_IN[11]}]
set_property PACKAGE_PIN T2 [get_ports {DBG_SWTC_IN[10]}]
set_property PACKAGE_PIN T3 [get_ports {DBG_SWTC_IN[9]}]
set_property PACKAGE_PIN V2 [get_ports {DBG_SWTC_IN[8]}]
set_property PACKAGE_PIN W13 [get_ports {DBG_SWTC_IN[7]}]
set_property PACKAGE_PIN W14 [get_ports {DBG_SWTC_IN[6]}]
set_property PACKAGE_PIN V15 [get_ports {DBG_SWTC_IN[5]}]
set_property PACKAGE_PIN W15 [get_ports {DBG_SWTC_IN[4]}]
set_property PACKAGE_PIN W17 [get_ports {DBG_SWTC_IN[3]}]
set_property PACKAGE_PIN W16 [get_ports {DBG_SWTC_IN[2]}]
set_property PACKAGE_PIN V16 [get_ports {DBG_SWTC_IN[1]}]
set_property PACKAGE_PIN V17 [get_ports {DBG_SWTC_IN[0]}]
