#pragma once

#include <stm32f091xc.h>

// ../../docs/hardware/pinout.md

#define HH_IO_SPI_MOSI_PORT GPIOA
#define HH_IO_SPI_MOSI_PIN GPIO_PIN_7
#define HH_IO_SPI_MISO_PORT GPIOA
#define HH_IO_SPI_MISO_PIN GPIO_PIN_6
#define HH_IO_SPI_CLK_PORT GPIOA
#define HH_IO_SPI_CLK_PIN GPIO_PIN_5
#define HH_IO_SPI_SR_PORT GPIOA
#define HH_IO_SPI_SR_PIN GPIO_PIN_9

#define HH_IO_SPI_PORT GPIOA
#define HH_IO_SPI_PINS (HH_IO_SPI_CLK_PIN | HH_IO_SPI_MOSI_PIN | HH_IO_SPI_MISO_PIN)

#define HH_IO_PPU_HBLANK_PORT GPIOA
#define HH_IO_PPU_HBLANK_PIN GPIO_PIN_8
#define HH_IO_PPU_VBLANK_PORT GPIOC
#define HH_IO_PPU_VBLANK_PIN GPIO_PIN_7

#define HH_IO_GP1_UP_PORT GPIOB
#define HH_IO_GP1_UP_PIN GPIO_PIN_5
#define HH_IO_GP1_DOWN_PORT GPIOA
#define HH_IO_GP1_DOWN_PIN GPIO_PIN_3
#define HH_IO_GP1_LEFT_PORT GPIOB
#define HH_IO_GP1_LEFT_PIN GPIO_PIN_3
#define HH_IO_GP1_RIGHT_PORT GPIOB
#define HH_IO_GP1_RIGHT_PIN GPIO_PIN_4
#define HH_IO_GP1_PRIMARY_PORT GPIOA
#define HH_IO_GP1_PRIMARY_PIN GPIO_PIN_10
#define HH_IO_GP1_SECONDARY_PORT GPIOA
#define HH_IO_GP1_SECONDARY_PIN GPIO_PIN_2

#define HH_IO_GP2_UP_PORT GPIOC
#define HH_IO_GP2_UP_PIN GPIO_PIN_1
#define HH_IO_GP2_DOWN_PORT GPIOA
#define HH_IO_GP2_DOWN_PIN GPIO_PIN_0
#define HH_IO_GP2_LEFT_PORT GPIOB
#define HH_IO_GP2_LEFT_PIN GPIO_PIN_0
#define HH_IO_GP2_PRIMARY_PORT GPIOC
#define HH_IO_GP2_PRIMARY_PIN GPIO_PIN_0
#define HH_IO_GP2_RIGHT_PORT GPIOA
#define HH_IO_GP2_RIGHT_PIN GPIO_PIN_4
#define HH_IO_GP2_SECONDARY_PORT GPIOA
#define HH_IO_GP2_SECONDARY_PIN GPIO_PIN_1

