set_property PACKAGE_PIN A15 [get_ports clkSPI]
set_property PACKAGE_PIN C15 [get_ports csSPI]
set_property PACKAGE_PIN A17 [get_ports dataSPI]
set_property IOSTANDARD LVCMOS33 [get_ports dataSPI]
set_property IOSTANDARD LVCMOS33 [get_ports csSPI]
set_property IOSTANDARD LVCMOS33 [get_ports clkSPI]