set_property PACKAGE_PIN A15 [get_ports SPI_CLK]
set_property PACKAGE_PIN C15 [get_ports SPI_CS]
set_property PACKAGE_PIN A17 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]
